name: "Release Build"

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: "windows-latest"
    steps:
      -  uses: "actions/checkout@v4"

      - name: "Set up Go"
        uses: "actions/setup-go@v5"
        with:
          go-version: "1.24"
          cache: true

      - name: "Install dependencies"
        run: go get .

      - name: "Install rsrc"
        run: go install github.com/akavel/rsrc@latest

      - name: "Generate icon resource"
        run: rsrc -ico icon\icon.ico -o rsrc.syso

      - name: "Build"
        run: |
          $env:GOARCH = "amd64"
          $env:GOOS = "windows"
          $env:CGO_ENABLED = "1"
          go build -ldflags="-H windowsgui" -o SteelSeriesArctisBattery_amd64.exe

      - name: "Create Release"
        uses: "softprops/action-gh-release@v2"
        with:
          name: "Release ${{ github.ref_name }}"
          files: SteelSeriesArctisBattery_amd64.exe
          draft: false
          prerelease: false
